sudo: required
dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"

    - os: linux
      language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

cache:
  yarn: true
  directories:
    - node_modules

before_install:
- yarn install

script:
- yarn dist
